//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAlumnoSinBD.SR_WSAlumnoSinBD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_WSAlumnoSinBD.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldResponse HelloWorld(WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldResponse> HelloWorldAsync(WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento WSAlumnoSinBDResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSAlumnoSinBD", ReplyAction="*")]
        WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDResponse WSAlumnoSinBD(WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WSAlumnoSinBD", ReplyAction="*")]
        System.Threading.Tasks.Task<WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDResponse> WSAlumnoSinBDAsync(WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSAlumnoSinBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSAlumnoSinBD", Namespace="http://tempuri.org/", Order=0)]
        public WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequestBody Body;
        
        public WSAlumnoSinBDRequest() {
        }
        
        public WSAlumnoSinBDRequest(WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WSAlumnoSinBDRequestBody {
        
        public WSAlumnoSinBDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSAlumnoSinBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSAlumnoSinBDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDResponseBody Body;
        
        public WSAlumnoSinBDResponse() {
        }
        
        public WSAlumnoSinBDResponse(WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WSAlumnoSinBDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WSAlumnoSinBDResult;
        
        public WSAlumnoSinBDResponseBody() {
        }
        
        public WSAlumnoSinBDResponseBody(string WSAlumnoSinBDResult) {
            this.WSAlumnoSinBDResult = WSAlumnoSinBDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap>, WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldResponse WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap.HelloWorld(WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequest inValue = new WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequest();
            inValue.Body = new WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequestBody();
            WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldResponse retVal = ((WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldResponse> WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap.HelloWorldAsync(WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldResponse> HelloWorldAsync() {
            WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequest inValue = new WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequest();
            inValue.Body = new WFAlumnoSinBD.SR_WSAlumnoSinBD.HelloWorldRequestBody();
            return ((WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDResponse WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap.WSAlumnoSinBD(WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequest request) {
            return base.Channel.WSAlumnoSinBD(request);
        }
        
        public string WSAlumnoSinBD() {
            WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequest inValue = new WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequest();
            inValue.Body = new WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequestBody();
            WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDResponse retVal = ((WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap)(this)).WSAlumnoSinBD(inValue);
            return retVal.Body.WSAlumnoSinBDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDResponse> WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap.WSAlumnoSinBDAsync(WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequest request) {
            return base.Channel.WSAlumnoSinBDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDResponse> WSAlumnoSinBDAsync() {
            WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequest inValue = new WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequest();
            inValue.Body = new WFAlumnoSinBD.SR_WSAlumnoSinBD.WSAlumnoSinBDRequestBody();
            return ((WFAlumnoSinBD.SR_WSAlumnoSinBD.WebService1Soap)(this)).WSAlumnoSinBDAsync(inValue);
        }
    }
}
