//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFAlumnoSinBD.SR_GetWSAlumnoSinBD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsalumnosinbd.umsa.com/", ConfigurationName="SR_GetWSAlumnoSinBD.WSAlumnoSinBD")]
    public interface WSAlumnoSinBD {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsalumnosinbd.umsa.com/WSAlumnoSinBD/helloRequest", ReplyAction="http://wsalumnosinbd.umsa.com/WSAlumnoSinBD/helloResponse")]
        WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloResponse hello(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsalumnosinbd.umsa.com/WSAlumnoSinBD/helloRequest", ReplyAction="http://wsalumnosinbd.umsa.com/WSAlumnoSinBD/helloResponse")]
        System.Threading.Tasks.Task<WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloResponse> helloAsync(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsalumnosinbd.umsa.com/WSAlumnoSinBD/GetWSAlumnoSinBDRequest", ReplyAction="http://wsalumnosinbd.umsa.com/WSAlumnoSinBD/GetWSAlumnoSinBDResponse")]
        WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDResponse GetWSAlumnoSinBD(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsalumnosinbd.umsa.com/WSAlumnoSinBD/GetWSAlumnoSinBDRequest", ReplyAction="http://wsalumnosinbd.umsa.com/WSAlumnoSinBD/GetWSAlumnoSinBDResponse")]
        System.Threading.Tasks.Task<WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDResponse> GetWSAlumnoSinBDAsync(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://wsalumnosinbd.umsa.com/", Order=0)]
        public WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://wsalumnosinbd.umsa.com/", Order=0)]
        public WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWSAlumnoSinBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWSAlumnoSinBD", Namespace="http://wsalumnosinbd.umsa.com/", Order=0)]
        public WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequestBody Body;
        
        public GetWSAlumnoSinBDRequest() {
        }
        
        public GetWSAlumnoSinBDRequest(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWSAlumnoSinBDRequestBody {
        
        public GetWSAlumnoSinBDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWSAlumnoSinBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWSAlumnoSinBDResponse", Namespace="http://wsalumnosinbd.umsa.com/", Order=0)]
        public WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDResponseBody Body;
        
        public GetWSAlumnoSinBDResponse() {
        }
        
        public GetWSAlumnoSinBDResponse(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetWSAlumnoSinBDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetWSAlumnoSinBDResponseBody() {
        }
        
        public GetWSAlumnoSinBDResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAlumnoSinBDChannel : WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAlumnoSinBDClient : System.ServiceModel.ClientBase<WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD>, WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD {
        
        public WSAlumnoSinBDClient() {
        }
        
        public WSAlumnoSinBDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAlumnoSinBDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAlumnoSinBDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAlumnoSinBDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloResponse WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD.hello(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequest inValue = new WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequest();
            inValue.Body = new WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequestBody();
            inValue.Body.name = name;
            WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloResponse retVal = ((WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloResponse> WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD.helloAsync(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloResponse> helloAsync(string name) {
            WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequest inValue = new WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequest();
            inValue.Body = new WFAlumnoSinBD.SR_GetWSAlumnoSinBD.helloRequestBody();
            inValue.Body.name = name;
            return ((WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDResponse WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD.GetWSAlumnoSinBD(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequest request) {
            return base.Channel.GetWSAlumnoSinBD(request);
        }
        
        public string GetWSAlumnoSinBD() {
            WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequest inValue = new WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequest();
            inValue.Body = new WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequestBody();
            WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDResponse retVal = ((WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD)(this)).GetWSAlumnoSinBD(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDResponse> WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD.GetWSAlumnoSinBDAsync(WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequest request) {
            return base.Channel.GetWSAlumnoSinBDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDResponse> GetWSAlumnoSinBDAsync() {
            WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequest inValue = new WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequest();
            inValue.Body = new WFAlumnoSinBD.SR_GetWSAlumnoSinBD.GetWSAlumnoSinBDRequestBody();
            return ((WFAlumnoSinBD.SR_GetWSAlumnoSinBD.WSAlumnoSinBD)(this)).GetWSAlumnoSinBDAsync(inValue);
        }
    }
}
